Relevant BUGIDs:
Purpose of commit:

Commit summary:
---------------

Remove pam_log.c, add pam_syslog.c and pam_vprompt.c for possible
files with texts for translation.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE YACC LEX LEXLIB LEX_OUTPUT_ROOT LN_S EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL HAVE_VERSIONING_TRUE HAVE_VERSIONING_FALSE LIBPRELUDE_CONFIG LIBPRELUDE_CFLAGS LIBPRELUDE_PTHREAD_CFLAGS LIBPRELUDE_LDFLAGS LIBPRELUDE_LIBS LIBPRELUDE_PREFIX LIBPRELUDE_CONFIG_PREFIX WITH_DEBUG SECUREDIR SCONFIGDIR DOCDIR WITH_PAMLOCKING PAM_READ_BOTH_CONFS LIBDL LIBCRACK HAVE_LIBCRACK_TRUE HAVE_LIBCRACK_FALSE LIBCRYPT LIBDB HAVE_LIBDB_TRUE HAVE_LIBDB_FALSE LIBNSL LIBSELINUX HAVE_LIBSELINUX_TRUE HAVE_LIBSELINUX_FALSE LIBPWDB HAVE_LIBPWDB_TRUE HAVE_LIBPWDB_FALSE HAVE_NDBM_H LIBOBJS SGML2PS SGML2TXT SGML2HTML SGML2LATEX PS2PDF HAVE_SGML2PS_TRUE HAVE_SGML2PS_FALSE HAVE_SGML2TXT_TRUE HAVE_SGML2TXT_FALSE HAVE_SGML2HTML_TRUE HAVE_SGML2HTML_FALSE HAVE_PS2PDF_TRUE HAVE_PS2PDF_FALSE PSER MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE INTL_MACOSX_LIBS LIBICONV LTLIBICONV INTLLIBS LIBINTL LTLIBINTL POSUB LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE YACC LEX LEXLIB LEX_OUTPUT_ROOT LN_S EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL HAVE_VERSIONING_TRUE HAVE_VERSIONING_FALSE LIBPRELUDE_CONFIG LIBPRELUDE_CFLAGS LIBPRELUDE_PTHREAD_CFLAGS LIBPRELUDE_LDFLAGS LIBPRELUDE_LIBS LIBPRELUDE_PREFIX LIBPRELUDE_CONFIG_PREFIX WITH_DEBUG SECUREDIR SCONFIGDIR DOCDIR WITH_PAMLOCKING PAM_READ_BOTH_CONFS LIBDL LIBCRACK HAVE_LIBCRACK_TRUE HAVE_LIBCRACK_FALSE LIBCRYPT LIBDB HAVE_LIBDB_TRUE HAVE_LIBDB_FALSE LIBNSL LIBSELINUX HAVE_LIBSELINUX_TRUE HAVE_LIBSELINUX_FALSE LIBCAP HAVE_LIBCAP_TRUE HAVE_LIBCAP_FALSE LIBPWDB HAVE_LIBPWDB_TRUE HAVE_LIBPWDB_FALSE HAVE_NDBM_H LIBOBJS SGML2PS SGML2TXT SGML2HTML SGML2LATEX PS2PDF HAVE_SGML2PS_TRUE HAVE_SGML2PS_FALSE HAVE_SGML2TXT_TRUE HAVE_SGML2TXT_FALSE HAVE_SGML2HTML_TRUE HAVE_SGML2HTML_FALSE HAVE_PS2PDF_TRUE HAVE_PS2PDF_FALSE PSER MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE INTL_MACOSX_LIBS LIBICONV LTLIBICONV INTLLIBS LIBINTL LTLIBINTL POSUB LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -21927,6 +21927,90 @@ fi
 
 
 BACKUP_LIBS=$LIBS
+echo "$as_me:$LINENO: checking for cap_get_proc in -lcap" >&5
+echo $ECHO_N "checking for cap_get_proc in -lcap... $ECHO_C" >&6
+if test "${ac_cv_lib_cap_cap_get_proc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcap  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char cap_get_proc ();
+int
+main ()
+{
+cap_get_proc ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_cap_cap_get_proc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_cap_cap_get_proc=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_cap_cap_get_proc" >&5
+echo "${ECHO_T}$ac_cv_lib_cap_cap_get_proc" >&6
+if test $ac_cv_lib_cap_cap_get_proc = yes; then
+  LIBCAP="-lcap"
+else
+  LIBCAP=""
+fi
+
+LIBS=$BACKUP_LIBS
+
+
+
+if test ! -z "$LIBCAP"; then
+  HAVE_LIBCAP_TRUE=
+  HAVE_LIBCAP_FALSE='#'
+else
+  HAVE_LIBCAP_TRUE='#'
+  HAVE_LIBCAP_FALSE=
+fi
+
+
+BACKUP_LIBS=$LIBS
 echo "$as_me:$LINENO: checking for pwdb_db_name in -lpwdb" >&5
 echo $ECHO_N "checking for pwdb_db_name in -lpwdb... $ECHO_C" >&6
 if test "${ac_cv_lib_pwdb_pwdb_db_name+set}" = set; then
@@ -26949,6 +27033,13 @@ echo "$as_me: error: conditional \"HAVE_LIBSELINUX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_LIBCAP_TRUE}" && test -z "${HAVE_LIBCAP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_LIBCAP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_LIBCAP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_LIBPWDB_TRUE}" && test -z "${HAVE_LIBPWDB_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_LIBPWDB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -27667,6 +27758,9 @@ s,@LIBNSL@,$LIBNSL,;t t
 s,@LIBSELINUX@,$LIBSELINUX,;t t
 s,@HAVE_LIBSELINUX_TRUE@,$HAVE_LIBSELINUX_TRUE,;t t
 s,@HAVE_LIBSELINUX_FALSE@,$HAVE_LIBSELINUX_FALSE,;t t
+s,@LIBCAP@,$LIBCAP,;t t
+s,@HAVE_LIBCAP_TRUE@,$HAVE_LIBCAP_TRUE,;t t
+s,@HAVE_LIBCAP_FALSE@,$HAVE_LIBCAP_FALSE,;t t
 s,@LIBPWDB@,$LIBPWDB,;t t
 s,@HAVE_LIBPWDB_TRUE@,$HAVE_LIBPWDB_TRUE,;t t
 s,@HAVE_LIBPWDB_FALSE@,$HAVE_LIBPWDB_FALSE,;t t
